language: java
sudo: false
notifications:
  slack:
    secure: T5mWhSOQkKV1cMncFJ5YQtGwKXmNmFvsDj9AfX6bn+R1Frwz7CwmEY4RB1zPXhQbSNdlqK2dVeTzE8jvMPNpwVreW9njv78v0hccaG6oX+X3VxUbb6STq0rnwVSvoS1CF4DZQgCNkCngGuXoTuC9eGMV4WvFO/haN5+mMF+XKnTRno2nkgNUXPMEqqSzOfG5e3v+VOuHOk0ah1F9JkCVjuvKtEBPtkwyRGS37DAVzuLG3Go189heg6hppvg5UNtS9olw3MMDUQxJO1ApzjJxRrOt0pPmROTaKwh824zSEaDfsIZEJy39gOxqjd14Cz61EAIryMqgsBfNdlHOIvCoKgeBcMaooDTC9sFEJn/UUqIS+1w7vOjRHasHxoOKeQLhz85ux7FNVaUKlKvmgOGQkI7I0725saQelD2YvRjSYHM7FA1FWOH9ZNNw7uZJAzDB3XtTTewIhEtnot8ntVWZrTU6KLnoY3trx+EFb7t7V+eokpxjujrvgwEW6QQ1yr3x8/hhiyK+TW662MVrX3M6rxFazsixlQrYOLY1O6qH0sHtgNYMDWmagTkvVF9rSvHC5X4f7xSKbR2cBsiDbSVbvEaYcWYA/aoZYhn/tPnHcueYQSiHzHfhuNizZfrmkGoZd76hOC04YkAkR0Oi6pNupHMQr9ew2isrOXiCg6Co6kY=
deploy:
  provider: releases
  api_key:
    secure: EA02ppiSLG/wkkYsiHtqlCQ+wxb0vISBw/FIetilokdydh3wCAlJKkXf9XfVDgGGM759eIQgFDyBjAcSj5/ZjHS5LLH3Nn8YXnjJI6mYT0+iKAsGjelAeWYMZdEF/uQarN60eAjpytSa0y12BjDGLnhCJ4vtBwDJiZihpByKKVJZTffnypxjaC6hsPqKinDDWW+q8RxN1mhkwIoFGS6+lySenXpaDaJMC9woYSMXQWYE6glYS69t0S3x+UUmrBv1CrlDkl+EpgEeMv/BZ0HRlmSOSEJYJblX+Zx9TxJ/b4Hd2bzRkXOInydZ9KqAcnAJj8ksUm2IMKBTEtOV0Q58xNO6Xo+wNaSjFvZeI3/O84/8uu8gjcFqpyCZhFCpPW/8sZJ/8GknE/j4rGeRr/I6XNhXsHEBYw2xAgycpht3XXkTDOtalfh9gRegmy3LRjo2EuuPjUO2NDmrWnFcOinrzbDx5HfmYEN/059/mnjCCQ5OZaNtjd4oyT90VZGig+uo6IHrrBINR7KjvWmzeKb5etIO5kNjXHv+Dc+AIzIF9zaLjaGvY1GJb3vGVWd43zxX+etGRZ4FTvUKrNVFKzy/aBpZ1wmMEYDDnlGONBs2MRtyM2wV1QRMNe93XrGk9RKkp7hevBGY6nV/Vab6H1alx12K0B6QrWY40PbVokEmRD8=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-unix-process-plugin
