language: python
notifications:
  hipchat:
    rooms:
      secure: RzdS3EMrKbzK0FrRuxBSVTBS6Xaxy5yHJePfYB4FnRdHoUin/dwYH2Xke+i9k16MR6OvIEPIsoL16aRmPQ2rATijYplFuYJm2g/GLMGM5hraLTt/bDxGC9ddOa833y4JECdSOoHTdtkjgoWHZ4N7w9z7nYhesPXapP0y+en0Ys2ioJNzDF3zyJG8TZOVewbuq4EKxV+aCqLzpemC+6IdnPj6TZFQ5dBtAIkzE2+pyRbdjpJjOJZRvqE1qJB82U9eD7566nvt54vYUBfP6L3v1icUe2e1hWrBTircMeE+VlFK/eaGocT8CBO2tOMYBQxDdgNfurcnsRi+ER2nRo3AyKNy8HcjJyx04dasSg4Qj7q09vd6sHcmFtU8TaffhlXdeuFRqLdJ7ybXBtRqIm4+5AzYEYTCYrAdNOVlLlYnSp/veNgXFW9PehSw3g3NDKobzvZjfhFd/mTgW21LF1skaSG1vcs/DzNExR8iw6EAonM+7IYNMiJBUyLvRvHqZ+2aqGcP+iyPKAjxgHDousdMS2GcqoYJ2QCMIV+MclPcMRiBwl6GTOsAqTz11wgchSJJpcG/A1xUgPgMuLL8pIIoLlfxrvY609nEOcnAdXU/YjRsJ4SWn7DE1RQnJfNHEpqiLNzpxoIKIFx+nSlq8BjHoIRXaep5norsS//QrRNQXok=
deploy:
  provider: releases
  api_key:
    secure: MS1Ew0ZokaPbddtkvPuIPej+IhB+4sjVtfBIh5EXJAhZXUsyaB7ouqWgdL777KaxeuujGuVJcuCFpWxe+sMWuND/UkpXL0QkRnzKHxMxQO50TXtUx7e6EKV7lT6C6caG4X6nuDNc/4gnxUvZ0L732m2CJwD/iw1sp3au8f9b7uf31lnEv9cxZcPZAES8wmrA6wTx7oK1YuV3i1vPIVzq8PqKAC7VoupXuBwiQTGW1sG2lzi0794i7a6izVq9S1P2RYg4b15Vh/Y7YpdmngUihtOgbwcxpCx+yb1atovymmeYcvXYgMW/89+ngEVqt4getEQKDC/lmXWRtEwv70UYNJjuSzQgJ6mooUwvGkHleOOZyKnd/880rMfo6zeywLLsYwMJvE8tj0UIN80st/JxIIOHLU54AYnQ3hFxPcFDSP7P0zDNIqEPdjA+oyIJ9JzYwd6i5ZufTdclEqclYL4GlyvJot2ZlM4pGvSmDIX9s8T6lEhUlVeV39Lf2ZYcMYcoWuj8LQbX6JTd2KpuEfbZjDiEoA81qXImsm6cEN1+pPoofj5G5wgSYLQf49O9ZczG5Ne5+wyzQ13c3O9m8k0HB2xu2Bm1sBAmYlsoagxByMmC8PiG6UKTNfpnFPEqmIZ/h+YEYDsgpv7+rQbXfv8HOfE30VkvpFLRzEBm5CH3CAE=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-unix-process-plugin
